apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HwPdeq7u2+5qXfEZrLrLqu9FZ/8l2XTKL+1ic3b2x/d7irLWlIDnDQ==,iv:YyJuchJG+lDeYIywUWxqHXPzk3c/hAVmItz673ak7Lk=,tag:EM+duSLLOrQZbV7hE7CgtQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMm5qZ1V0Zmg5Y2k5Mktz
            NkFMRURWTlhsQ2hSeTRLU0VKcWRxa1J2VFE4CllCaHdBOUxoYmdPYXRLaEdNWFZJ
            bXUxSGNTY1JtTUQvdU9LT1ZmaWR1RG8KLS0tIFN0OEM0aWlkWWNSa1V0aFFkb25u
            Um9PMG5FTkQ0cVhxQ3hxak01SElnMlkKNv1UElQC8NOJPTJj1e8cjzoh6WS+SAox
            6zTz+mEiC89mEFqhPyYdgjUv6/mGm7NinbbCGwVcctgu46u8dywPJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T08:24:02Z"
    mac: ENC[AES256_GCM,data:IlMgXyNL9a96wOAbwR+QgLepjGHRsAQDmqhj2zOKgr85lylQM4PQzb05BHxUPCO60j7t7ZQUBKQWOUyqUH3v5yy3HhZUHV2kK/qX9FtkLI+pJWq/rIDAMZTHvnhDPw952oLSK3WOwd55IzfpPMc71SvFWCkB/CPq+CHvFsJCYt0=,iv:kBqV1BKIYLOpRuANSh6b7o0TXsI1lA7FSU7iMIa9pPY=,tag:rWVCiHh830JGtPGbdyPjJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
