apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+ARGtkQrouI9F3iTTlK43j5YcajN/h2cJe+r2kzAnB7NRsuNRZl6MQ==,iv:1lHx6VfDjxFMjGZlrPo7U3AiRW5hwViqViLVJ4ub+b4=,tag:eAMOUm1dOXi79YdkpWMc+A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dlBvazkwS2VOdkZYdGRo
            OFJXZ09hOXRscTNWMGVlMXJpM2w2dUxVZlc0Ck9rOUxyYjI1a0poMDQ3V21Ea2RG
            M0NONExGQi9PMFpreUhaSDBKeWJZdG8KLS0tIFRoMy9KVVlVazhHS2RYVjZIR2lQ
            ZzVicUJNcWlJY3BtWVdTeUNZY0Qrc3cK5fNS4QsaeIjrE7Zdfj25S4asXYuR1AaU
            jAFGFlJk+Ul3aQOvUDeE7xOqCX5ICLp+HYJfxbieE18fAj3rJgizaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T17:31:13Z"
    mac: ENC[AES256_GCM,data:Ou+KUqgADn0UW5ff6jOgsVtlvRDowoqpWrwRfHtwA6L4zhMzv7Y5pF4SlkOvgilZWmQwYeHDCQhLCGfbF/eW4WOxqSFYml0QULZbVxJTcKzAUEP5HHOCSrKlBFtLQ0cz6xrQprkHwKSllZgG32vJwA+9HmJJU2VJAIHY9yFWlYM=,iv:FXbfN/9tamunurab6oLx+4VZr1id9gdWMFMKQVlFGJ8=,tag:3hpfExDyFS3FKjNQhCcxBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
