apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:etwzBOoCuRbb1K7Eo937NYqRaDAT+L8HijZkmxmZBqi2+4NCaQHTjA==,iv:K2HkNUmS2qof/mPyNwAFuqi5J83N2/e3JfGe61DGLKI=,tag:/Ri9FxxdfqgqYYf/rauiaQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbkE0eU15STQ5Zkp3cjlj
            Rm5WR2dpUjQ1QXd1cWV1UHNoT0g0QzFtMVNRCjZyMkxMcDhBSlRVVlNNZU1rK1cx
            Y2Mwa01pMFc3Q21IWEg3bzI4cHd6bVEKLS0tIEM4WW5xMlo2NEdIN08wOEVHNm90
            UjVWMW5oYzQ2SGNGNUlXOWxWRlF0bk0KqZgPOynUx+UcO9VVCnx5QDGXc5SxBjyU
            HRRA4QyS+BQvzC4xjXj4Dd7o6ajLhT9C+CwttkWxsfSg6Et+aMWEqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T08:43:23Z"
    mac: ENC[AES256_GCM,data:+Lqtz1USareh8Dm4IivwccghZ9k5asOPdOQCBBCUOgmLSIY0XQjpdxrRO/UmQ7O0OECOla9BqSq/Z3LXY6ml6GCKJAp78RF28oqMhEmUZdoPynjQg2w0uvxvYI1uPuci3cS6SMKzYzxEiYsTpy/lV+XFcgHeXLFX2baF9JGj/i8=,iv:3MH7fN3f+PcBUuNpGAomzv3MQmm0Dc1R+k/m3vUMTgw=,tag:JOxqfrSXP2pESelH7tZO1Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
