apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-enhanced
  namespace: jellyfin-enhanced
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      version: 22.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENC}"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-1-le-prod
        hosts:
          - host: jelplus.${DOMAIN_0}
    resources:
      limits:
        cpu: 8000m
        memory: 16Gi
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
      data:
        volsync:
        - name: data
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
      ssdsafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_SSDSAFE_RIPTIDE}
        mountPath: /riptide/ssdsafe
      videosafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_VIDEOSAFE_RIPTIDE}
        mountPath: /riptide/videosafe
      videounsafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_VIDEOUNSAFE_RIPTIDE}
        mountPath: /riptide/videounsafe
      videounsafe2:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_VIDEOUNSAFE2_RIPTIDE}
        mountPath: /riptide/videounsafe2
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                JELLYFIN_DATA_DIR: /data
                JELLYFIN_CONFIG_DIR: /config
                JELLYFIN_LOG_DIR: /logs
                JELLYFIN_CACHE_DIR: /cache
    autodiscovery:
      enabled: false