---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 21.10.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam
  
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                GF_SERVER_ROOT_URL: https://grafana.${DOMAIN_0}
                GF_PANELS_DISABLE_SANITIZE_HTML: "true"
                GF_AUTH_GENERIC_OAUTH_ENABLED: true
                GF_AUTH_GENERIC_OAUTH_NAME: Authelia
                GF_AUTH_GENERIC_OAUTH_ICON: signin
                GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
                GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GRAFANA_OAUTH_CLIENT_SECRET}
                GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
                GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES: false
                GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.${DOMAIN_0}/api/oidc/authorization
                GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.${DOMAIN_0}/api/oidc/token
                GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.${DOMAIN_0}/api/oidc/userinfo
                GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: preferred_username
                GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
                GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: name
                GF_AUTH_GENERIC_OAUTH_USE_PKCE: true

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: grafana.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: "Observability"
            weight: 1
            widget:
              custom:
                version: "2"
                username: "admin"
                password: "testpassword"

    cnpg:
      main:
        cluster:
          singleNode: true
    
    configmap:
      datasource-loki:
        enabled: true
        labels:
          grafana_datasource: "1"
        data:
          datasource-loki.yaml: |-
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                uid: loki
                url: http://loki-headless.grafana-loki.svc.cluster.local:3100
                access: proxy
                isDefault: false
                jsonData:
                  maxLines: 250

    dashboards:
      grafana:
        cert-manager:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          marketplace:
            # renovate: depName="Cert-manager-Kubernetes"
            id: 20842
            revision: 3
        cnpg:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          marketplace:
            # renovate: depName="CloudNativePG"
            id: 20417
            revision: 4
        flux-cluster:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/cluster.json
        flux-control-plane:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          url: https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/control-plane.json
        metallb:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          marketplace:
            # renovate: depName="Metallb"
            id: 20162
            revision: 6
        nginx:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          url: https://github.com/kubernetes/ingress-nginx/raw/refs/tags/ingress-nginx-3.15.2/deploy/grafana/dashboards/nginx.json
        blocky:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
            - name: "$${VAR_BLOCKY_URL}"
              value: "https://blocky.${BASE_DOMAIN}"
          url: https://raw.githubusercontent.com/0xERR0R/blocky/refs/heads/main/docs/blocky-grafana.json
        blocky-postgres:
          enabled: true
          datasource:
            - name: "$${DS_BLOCKY-POSTGRESQL}"
              value: blockypostgres
          marketplace:
            # renovate: depName="Blocky-Postgres"
            id: 17996
            revision: 15        
        volsync:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
            - name: "$${VAR_REPLICATIONDESTNAME}"
              value: '.*-dest|.*-bootstrap'
          marketplace:
            # renovate: depName="VolSync Dashboard"
            id: 21356
            revision: 3        
        logs-container:
          enabled: true
          datasource:
            - name: "$${DS_LOKI}"
              value: loki
          marketplace:
            # renovate: depName="Container Log Dashboard"
            id: 16966
            revision: 1
        arrs:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          url: https://raw.githubusercontent.com/onedr0p/exportarr/refs/heads/master/examples/grafana/dashboard2.json
#        smartctl-exporter:
#          enabled: true
#          datasource:
#            - name: "$${DS_PROMETHEUS}"
#              value: Prometheus
#          marketplace:
#            # renovate: depName="SmartCTL"
#            id: 22604
#            revision: 2
#        truenas-exporter:
#          enabled: true
#          datasource:
#            - name: "$${DS_MIMIR}"
#              value: Prometheus
#          url: https://raw.githubusercontent.com/Supporterino/truenas-graphite-to-prometheus/refs/heads/main/dashboards/truenas_scale.json
        longhorn:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          marketplace:
            # renovate: depName="Longhorn"
            id: 23521
            revision: 2
        k8s:
          enabled: true
          datasource:
            - name: "$${DS__VICTORIAMETRICS-PROD-ALL}"
              value: Prometheus
          marketplace:
            # renovate: depName="k8s"
            id: 15661
            revision: 2
        node:
          enabled: true
          datasource:
            - name: "$${DS_PROMETHEUS}"
              value: Prometheus
          marketplace:
            # renovate: depName="Node Exporter Full"
            id: 1860
            revision: 42