apiVersion: v1
kind: Secret
metadata:
    name: doorbell-turn
    namespace: doorbell-coturn
type: Opaque
stringData:
    Ice__TurnSecret: ENC[AES256_GCM,data:HqxSG8WC0//jq4zo4nqY5qmiQSwwtqLlXraOmLsm66dLXeYvIuaP1erakCE8qpq3A+WFvyDFMvcT3oc5bAhzCw==,iv:tVBl+z7UOijcr4D4o6lRJjrjXaqt8NbLWnF1g4r53sk=,tag:QNntPTBaxcBkzJL3QtzZBQ==,type:str]
sops:
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTlEvdC92K2haMEpiWGRy
            RWs2MTdFZ3ZXUWFVYnB3OXFCWE41b3VwazFVCmovZEJzQXN1ZWpabXlBSmNhbXFh
            dWhKb0pMY0EyL1RacXVHSW5NWGx3ODQKLS0tIDlHSlVNcER0aS8yQkpTbmZ1Vjhk
            R0VwdUdJRHdaMkxVOW5oUFRCVzBpRTAKviiRshNoIC/8zkNXQ0aHa4PhOj7g+Gde
            nkbG+Fvej6S2iEE0g5HRnibfeS7J0a0RvulAhcq17r/S7Rd1deCzHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T14:31:31Z"
    mac: ENC[AES256_GCM,data:f0qaMYSlJDZ2Bg4fDihBG6N3+wXFx8SGKliRG2L8AWPmLKN/mMJC6pUXvBuiHUlU4X/QjmY8tnDO4++enqmZ09m7r2zIOvya6tIR5We7laNCR+919jflGCQwvPCeBJCTvpS4USECrR/2hnif3KEAhiXwX6aL/fmQyyEw8Suc4o4=,iv:x2RmyguZAbCayrZcPUGffIEz6gS2BbglAZk9nPTW31w=,tag:08VEKaxqhPd7y6wp/X0jJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
