apiVersion: v1
kind: Secret
metadata:
    name: doorbell-turn
    namespace: doorbell-coturn
type: Opaque
stringData:
    Ice__TurnSecret: ENC[AES256_GCM,data:RU+T4vk90nrpXlGCOq67W3VM7zwNz4UTfhfRGOR2lCROVKY5OtsTB6t0cbImXi78FL0yVLG+AWUAu2YEKm763g==,iv:a2tXNZsx1BO1HuG6lTk/wx9KLz7DKVevA/G61GGg+hk=,tag:ReChYkTlA4ZLZuBRWm2EMA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQkdMendFeXFIMHBmU1da
            d3F4UmpyM00walZqU25VeWhmSUNPRER4UHgwCm5zcjhCYmwrM0NoelUyVWZIWjVN
            TjZOV1ZCVnNqd3poODkvTkVSWDhiUDQKLS0tIDFHK05ET080V3orWHpPTFlzb3VK
            V3ZWWW9OVEpJeXR5QVlWTThGc09HQzAKw/wGxNlFfb03Zjm/msnWScZpoXVMIPR5
            /9qseWKCH+pMLnzrQYXZ20SPbFH0IAVNCW2l3s3p9OH4c77JIuvxIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T14:15:59Z"
    mac: ENC[AES256_GCM,data:BWAa4jxZFMuuytGVtSYVwCrHrlgXkGmXUX8uRY2NKT2G0OLGlT9ur8q6rjF8laHKyWyN7q2VuArSC7+lh/tOTS/p0cp+1ZpktYORfZqwWfMk/QG7nSAzg5mdiUuQmYlxGl8hDYnVh6g1gfSOEA6SOofHJVovHrDheZGWc92iWKY=,iv:UOPBQk8phKP9pjG7H3hDbySxInMHCUPvNChobDaDyyU=,tag:0IrxAqlq+HiyEDnNK5ATzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
