apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps
#  - cloud
  - core
#  - external
  - flux-entry.yaml
  - flux-system
  - kube-system
#  - management
#  - media
  - networking
#  - observability
  - system
