apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps
  - cloud
  - core
  - demo
  - external
  - flux-entry.yaml
  - flux-system
  - games
  - kube-system
  - levendkompas
  - management
  - media
  - networking
  - observability
  - system
