apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-makoto
  namespace: nextcloud-makoto
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 43.0.15
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    global:
      stopAll: false

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENC}"

    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: makoto-cloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
      admin:
        enabled: true
        ingressClassName: external
        targetSelector:
          collabora: collabora
        integrations:
          nginx:
            enabled: true
            auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_0}"
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: makoto-cloud.${DOMAIN_0}
            paths:
              - path: /collabora/browser/dist/admin
                pathType: Prefix
    cnpg:
      main:
        cluster:
          singleNode: true
        #mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions
        backups:
          enabled: true
          credentials: minio
          scheduledBackups:
            - name: daily-backup
              schedule: "0 5 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: minio
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 10 1 * * *
      data:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: /${NEXTCLOUD_NFS_PATH}
      html:
        volsync:
        - name: html
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 20 1 * * *
    nextcloud:
      # ClamAV (Anti-virus for Nextcloud, keep in mind that only scans files that Nextcloud posts to its endpoint. A Clam AV container will be deployed automatically.
      clamav:
        enabled: true
        stream_max_length: 26214400
        file_max_size: -1
        infected_action: only_log
      # Notify Push (Allows Nextcloud to notify clients of changes, instead of clients having to poll. A Notify Push container will be deployed automatically). This is highly recommended to keep enabled.
      notify_push:
        enabled: true
      # Collabora (document editor for Nextcloud. A Collabora container will be deployed automatically.
      collabora:
        enabled: true
        interface_mode: default
        username: "${NEXTCLOUD_COLLABORA_USER}"
        password: "${NEXTCLOUD_COLLABORA_PASSWORD}"
        dictionaries:
          - de_DE
          - en_GB
          - en_US
          - el_GR
          - es_ES
          - fr_FR
          - pt_BR
          - pt_PT
          - it
          - nl
          - ru
      credentials:
        initialAdminPassword: "${NEXTCLOUD_PASSWORD}"
        initialAdminUser: "${NEXTCLOUD_USER}"
      general:
        accessIP: ${NGINX_EXTERNAL_IP}
        default_phone_region: NL
      previews:
        providers:
        - BMP
        - GIF
        - JPEG
        - Krita
        - MarkDown
        - MP3
        - OpenDocument
        - PNG
        - TXT
        - XBitmap