apiVersion: v1
kind: Secret
metadata:
    name: makoto-secrets
    namespace: web-makoto-backend
type: Opaque
stringData:
    JBN_USER: ENC[AES256_GCM,data:Go8eTTdERfwB8MPHmNTvyIZquARXeUBdra7LtvyA,iv:h2fzlmi4f6e/2sd4jsEbtRp97U8rkj4T+8gmabcWwBE=,tag:r96/t9932CUP/dNXzcpG1Q==,type:str]
    JBN_PASS: ENC[AES256_GCM,data:uaCdfnIQSLWubUnsM0X9rPYPkzMO5siGPMpxFKgmkFigrCcqPscQYw==,iv:IyMWs4LcIM9MOMRRR3CKYqdmvCbByAU3ZCBZYOCROhQ=,tag:KF50Z5dNcW9Yeg2/a0ybdA==,type:str]
    JBN_TOTP_URL: ENC[AES256_GCM,data:KjZfnoSNSXzpEkUKPO1DhXk9cQv5VFUgg/HkG9nxTKKncBZhLUUmxwycMViNP2oAE5wHTl2hXusHN6o/ZZF99iFEPnG0yjdLFvv8JMY9Pmrg5/eoFsMLFER6qShbpv/dGvx2EnxHPPhrpjA7+XNr,iv:3X2qd9O65/TI+MHr9HJXJ25OJgDCAANF/scnzTCV5yk=,tag:RPcZO7/kF/Rne5k9Eyo07w==,type:str]
    WP_BASE_URL: ENC[AES256_GCM,data:QFpyMac4PtcsBMjIc4RLMMf2sx5oBg56Unf7OhDhHg==,iv:hxSzEMbTRm0ZZJJBkwiTWMpbaeLA4n00ecJ8YvwzX6s=,tag:5fVN76kI3XZOcCkzWai9Dw==,type:str]
    #ENC[AES256_GCM,data:fjOPyg9FoEFNCY7AzGNJhfLMJgGBefx+U5U+yFZm,iv:IxW3O7DnZUpi7BCQfIleMCizZ0JdBWb01stkMVubBDY=,tag:tMA5bxpR7rv0OHdZG9byuQ==,type:comment]
    WP_USER: ENC[AES256_GCM,data:KaT+44YCMnaJGQ==,iv:FaI6xOLmypdAW82NtSjxIJfvR4LLZlGZzikf+RK/RpM=,tag:uJTyEReUHT0gfZxK7u+hOg==,type:str]
    #ENC[AES256_GCM,data:tAf5raW2+6+cz7lRIm6eP72FjBr1M/MkiQ==,iv:4JUxG4VVciIBFHfU037h6Ai0/Ft08OOvY36OmVE5idE=,tag:agZgH0Ph302N/ya6H8LDhQ==,type:comment]
    WP_APP_PASSWORD: ENC[AES256_GCM,data:h0nggGLJKJvJdfIq6bxEIaNNpMueBIVvftA/DJU=,iv:aBaV1a/1mCZlvVixH10mjPfG4f+hfV74/3XFXiFQGak=,tag:7UpDuuAhwlKKtObUjpqraA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1KyszWUk1bEd4dDQwUnFZ
            b09hWEgrSmI0QWp0bGJ0alpmUjlVdDVsckdJCksyTnNEaS82MExRaHRMZitjU3I4
            SW82a0k2Q1JjWjYxS1VRdzN1YnU3a2MKLS0tIDRUTVc4RDlIN1VnZ29Od1QyL0FF
            ekZ5OHdlRGw3OTNXMWpMZ3YvNFdCTkkKwvCFTaPjLv2KWcGqzfgfKmCZ+OEQ3Gul
            if2qmewZjJDRAmE3pHi2fWZNbZNxzAmilrqnCHNt5JNgH1SHpipbhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T14:15:59Z"
    mac: ENC[AES256_GCM,data:qFzD50vyLADxTtuIcSG1GkyNFXYHy9uXoHcSfaezlmt/pHcmLY1/I9xiysCdtW7Xk2z5V78pzztiSsColpYnMja4co0Uzmq9YGoq4uN0Hr+wO5Ru14BPVkA4tEc/MJmg2rW/OO4Zz7le3mJDaMW3LDSSBdNZc4oQcjxqd2AWBeY=,iv:noyAvfi89tXmHTHz2Q/G5Y7CcStclj06hX0uHcxp6JE=,tag:84vvaFQKn28R+vFpSYzW+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
