apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tkqmkiYqNrFzsmF9AdfAbbN6Uiw0WaVDdKSPH51zBxMQtcVLKg7NVKEQowXWRNYtlL8JdClnROWHjgHMi2eRxENUv+yGa/zBpxsWcGKY6ia+zSdhqDd2Y/7cPnQnzceR9Z8k2uECBA82Z+k3t60epycLOQQogLRWsDVUxuWvP3sUdXT+0eBZLcAqM/MnduyoDnFccxy1SFbZdIWw54BVIGy51iubxyy2tmh2JgAOnCY9BusxAM+X3T+eCHCkVb19YoDd0D9wzgalfcUFxnzwRmS9+JZyVG0cccBvEmhL+Czk9DeVlSzzI+wr5AW6rqv2R3wbqV3OoQOm6zj7BbbfILk/93/ASx34YmGujuHMYAI4AkswDsK7WUy4EojBcxio,iv:D7GxyDy/flL6OqgkuW/Kjee858y+VQbEN1JOjgOvYSk=,tag:UqjK48YZYhz5ghNkCYopZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:z3NtcPS0/31SSUDfu2UZuefH/6aquQiVSYWa33yYP6psW+7uUaPGAVrBVzzjhgEop4OfPDC+Bx1wAp+VMLRiu1o+NP9cEWJF18zbON5UhgqM+NIz5uBsVVCuKJS6mpzF4+sFT8JfbaUITIBGebX+3T8fkc3pl2bXtrD87noqSeQxH8a1LMHo6U2FuUufWkQtTZsCx6rNwEamrJv04elsuy9M9Z5QXduuAiqcjvucLl4y1QO2QbSlYRDQHQfg1piMS/iB9Tqul/hme4Md/g==,iv:BCNU2mQu7LuMsfH+crqn9HXFO+UCyQ26XebW/oDD2Y4=,tag:d8jTPtE0cp3q+TkkKP1qfw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gylp030IuhwnTFN4dppPLwdFWNhV6kkK9jfKR+u9NscQ/snP8UhPbx/vMjLr+sF/fdsZvIA0peVEH0qCMmtIaUDUJU8XmGYP50T+zR7IAx8+//4T97qtyVS3LQarkwkYgDXSZs1XwaLShasWJnTQdvpl1j/SlwnROTjqyuGs7z2q846f99TGTp8kvnRXhfGuRVmVnZ4Ss8vaLBV1DijilmQKPnHNjHWeCEzU,iv:D66rTZMb/rKH3fFKVAS+EQkQcZxIbhDyT1z1WSAwCfY=,tag:DsrYH66hJXRTCBELzFuK4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY3pHZEZrUytlQW93THg5
            WUFSbE95THQvdzdMa3laWUtnWWowZ3Q5bnpNCmlrN1lYZm9jTEpFdCszQ1Zmd01G
            cm55UWdQUlBQWlRsTi8rR2RzaVVEbzAKLS0tIDQrd2RkVk1zQjFNM3RQUTBFbVJi
            WVlKODNMZlhQa0VmZHZ1ZEw5YnZmREUKHA0Veb6oXbI1BWHmjAPo6GnNxkut3pHv
            inH0YEnTU2hJb9nHr1ku5MYT1hWm2bXyrZ6L3+Cl9noXQ7e1tOtXOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T14:52:37Z"
    mac: ENC[AES256_GCM,data:JtToZLgnRqZuklsdWIMXhHMh5a6Snvzsz+FM9ZhH6fCNlGxcWGlW909AaxQJ+Kn8ZQhi+fP273gOqV2f0k+xVAe/TJrWrfgQ0V2zZgmviTxvdJ2enLy6IDpvhI2okJifjdjgNFu7Pyyndi1Jgji/XkA5SlOoCH913+AzPWtCPiI=,iv:Jl6VRf2rLrsL0w/V3KOnwXKw2nH/zephApF63nl836A=,tag:buEG0gZIx5myxFSMdcGfxA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
