apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yH9InMACXaYvJ7FHdvckLrrdYAO1jKKg/gxU6gNX8x+ht8mh8QEEnseoJZaKcnZzu/5sIaTYIDdrImMlaxLfNKO95Mlf/pabPKPzoHMYe0TfV6T+7Ilj0xc5/Gly6GBDsGhDLKTSF/ZgCEs+IT/i+9jjmfPRjOA+upccndeABnc3vufZZylis/52lN7q025QqGLDEqn72T4m1HBdxv6rMkkkIIFFokVIaZ7vHTaQlPaKF9J79HwF13xeSntIxJWW0E7qY4mn25DcgB+EAHHh2vEmc9oVx+1Xvy12RqZ9uj68rKHru68n1w3gIuS9qh3XqQ124/NBWb4L+5c1LrmRQ7tN3sJVSX4W6oGk3xi1REzmyDs49B1bV7gNqZEiigTI,iv:0pIT/pJ1aWv351qjx6Xxr9YNKsLPPNRkxLq1L8j13QI=,tag:YOVyJZj3jebO/rJNyoW/9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:JSqwbpoSyugq8AiBhJV3PEeSAJLaAc3wXhwSf211DNOSyhoNBxwk2xidcZz0VY8hMBvc91vJvQ12GLphZMCFJXvw1uufIfDhglMG0dnVl/k1CTfrPq163AieZ5nswSu+gK0WP2KgbXMxwKvde2TttuZ8JkQMiOrqN+TPiglmAHBmM6QS5dsu6fIL+0tLH8igdb5aHYchWBzTuXZxmfHeuOu5lTY9co+KTq5EX8sI66RE/cigCjXQr5U7fk5orhtgk8mwcQDtvYdgUL2FQQ==,iv:7/uRxSe3uLtwFMdEpNfexoNs+712KSmBrLfpShdKAAk=,tag:h2IM1sea1dF99E958OBWjg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xqoZzYeUpanrap1o4MdWBd0esKdVfU0c8kfI/mUxhw8eAt42rNdXacOzyNIz1UYBtCdrKFt2/JYuoD/KgPlAPvQG0rkPRest6P48PURqFHC4/fn06Ke7N/UWinjqPimQxYdiL+j8UHmOWndHIA2OtXhIZkIAVbTz11ZdCDW1DKOl1Ti1vpbzoo2Daw+IlxH4cgOd7IqRQYqehUiiw8We4xd1gTGQV0iYrj7v,iv:diXlMJfct3DqJIns2N8ny0gIdgcjHKcAsE42p/HPbOo=,tag:L9iDANQFsNeYR3bcdwSPpQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZGtwY1VQaVovUkI5NGZN
            Z3l3endqK1JiemtaNkhyYmRIb0NWMDlMamhvCjFSU1pjRWl1ZTk3bUNYejdrQVk5
            NE1qaTFhaDBGQzJTeitoRGJyVW00N2cKLS0tIFNJQ0Q5SnZhcTRRZkU0OUtlNWdz
            V1NTN29ZUXdwdGtnYytSRTB0QytOOEUKWNih5PTfrz+N+BRz+3v48h50c2BZ+Hly
            vMzvb9rNbwW6/id43JT/iDLmcM8pSuP11Be08ayKVwHBztw9/iCUeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:54:59Z"
    mac: ENC[AES256_GCM,data:BnizlJkISa9HxwAlq+c5kTgWdpw5NDnBSTVl2ym3qupZrFkw7AfWH34mcTteia0mu7ba6PfPCI7bGEsR7PQldAY3yx0JGOyp6w8BvMR00hK5xFSu719NmN3eKdLyLGdeR95NNp1lAa5vbRr+2kDWRVPrPmBi5dude2ErD11JBHY=,iv:4kcobTUMTz++QDD8xkmKwyZNjk2xczEwuTZp8AZSXfw=,tag:hdwz1BXMEF6R1xCjtHO5PQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
