apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6ovA+fv+DxR6de+cgMB6k8/QRq5YfQU7G/qJvLY1vWldxxaegMG/9kmS0ll8cR7xsHo7l7IFJs23BvtQvLn4NcDMsflIgqIfyYcSnZUg/JLkyUo+aFP3a7HAY1s8kn81gFWE7kQx2uFy4OHPRMUkivq2wF6uhbEcpxQifTHDoOgkq6lkBdCA8Wx1a0J+st5b9g2zeFN5rHDBpDZv5zBKYb7k4OWaSg3oCCSqQta3EqaQz11nocNyuCxdpt8vbLCPZN2oeDfjJU4rGHMTZCA2KjV7H1mS2j1p2O3iP3meyV6BUddo6LnErbWhqNiDWClhbn/kVahSC+xOV+Ot1QUvZ7TzLiMKNyMSirmiCBAWCXlMrbeIUc9iI1I7svIyK7ny,iv:oUhfRqLCwAgqraRJNIvwjf6Ot/SivfI64jOCtATbok8=,tag:ol6kjvJVAjHirO6L3wSS5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:sJR8e6vI9+kUDk4R6F2PWUv2qIsZUyNxwF6Xh2eGoznG5N04YB2bS5vdC0IzI5vtjntQITNCyPDVRzRsWzLr/vgVJnRcav/4WqExIiwt5Mb5L7XGIKuGqj+eSSyTFTYRjOXrvbq/MhMRyi+Bzm5HokoJ12E1T/4KUlc+1SJEFcA8zz/V/koCEKKKNlmLLhav6rQnKBx499OWiiDTyOH945d8MgXTBhdBtjcqs6uHlWUppE+J9ji6GJHi4GnHywLC3T+95vo1BBuJEKmBYg==,iv:54yfwHgpFnJzwhJCO31pHJjUf19b9UbNORHsRtD8tck=,tag:7QcoEWEMYIEWIoTKQFezkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:jts7RU/0/mPlku1Y7iu8Gnl+WIt5PoMG/YwQzmtRQ0nrdZ/dQxY2vu/+jdhyHZvQzrMo7S+AyOn5qiaT9bbnGvdL4TEO4m4cN4e88MGyMZBcA0S2gqzGVN2xLD82tw0ZI86I1OuHiswsV5lDyKm6/1Gh0Nvj95njQy9SvD9wu9DQt223S1uF6n6V7nBSyKM2+JLuSvC9gq1ORvoOMzxThzX8XFzq+zbubhrb,iv:wafrJGQJtugiEJCqeKHeHwfJDHRZW4OOsHd8JTYDKfM=,tag:F5ZA9NUJtvbPppcdY8Y4vA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQmRjYVFRdUxpbytuNzlp
            ajFULzZnNTA4TG1XRVpURDlGL1NtU0JwRzNNCmdQelc0VFJRalpGV3ZGMWdaRko4
            ZHhUUVEzZFI2aEhYbmNnWnV2eHVtSGMKLS0tIGwvU3F6blc2UW5Ud0pxamx6SWJj
            ajBRZUJqSkNQVC8yR2ZZb2dsMGFvL0kKcs7H8Piu2OF3PQtCSnw33dzBkWbAsXnF
            YEg/ObU0PBcyZLjaMeP2iqKgZOG+5eVWR4vMqBDs0Xm6qFvDC67VQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T08:24:02Z"
    mac: ENC[AES256_GCM,data:CBScCmUGJ/v1nom4RZgVtwYFKHlReYytkAsk4xmCBShQ90+LJvbyRVjLLpQmh2LRa7TrAlFomsoFrtUWCwaBRmf0w10QfgjWE//7nvoI7MGntQjlNmRK3+9RgffCGAuz/OFwv/F5iKFqFqQsLpg5zIEM6NLWp8G6eAzCK72FgT8=,iv:DDQWneaax1okrIJ+4rw1i4YumHWtNHIuUfCsNrPqP8g=,tag:RqgiFJjgRng7azXyru7sUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
