apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: daisyfrontend
  namespace: daisyfrontend
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 15.38.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    image:
      repository: registry.riptide.live/daisyapp-client
      tag: latest
      pullPolicy: IfNotPresent
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    service:
      main:
        ports:
          main:
            port: 80
            targetPort: 16080
    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: daisy.${DOMAIN_0}

    workload:
      main:
        replicas: 1
        podSpec:
          containers:
            main:
              env:
                VITE_API_URL: http://daisybackend.${DOMAIN_0}
              probes:
                liveness:
                  path: "/ping"
                readiness:
                  path: "/ping"
                startup:
                  path: "/ping"
    resources:
      limits:
        cpu: 100m
        memory: 4Gi
