apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - watcher/ks.yaml
  # Sub Folders
  - administration
  - requests
  - streaming