apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin/ks.yaml
  - jellyfin-enhanced/ks.yaml
  - plex-backup/ks.yaml
  - seerr/ks.yaml
  - seerr-jellyfin/ks.yaml
  - watcher/ks.yaml
