---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 24.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    qbitportforward:
      enabled: true
      QBT_USERNAME: "${QBIT_ADMIN_USER}"
      QBT_PASSWORD: "${QBIT_ADMIN_PASSWORD}"
    gluetunImage:
      repository: ghcr.io/trueforge-org/gluetun
      tag: v3.41.1
      pullPolicy: IfNotPresent
    configmap:
      gluetun-auth-config:
        enabled: true
        data:
          config.toml: >-
            [[roles]]

            name = "qbittorrent"

            routes = ["GET /v1/vpn/status","GET /v1/publicip/ip","GET /v1/openvpn/portforwarded"]

            auth = "none"

    addons:
      gluetun:
        enabled: true
        container:
          resources:
            limits:
              truecharts.org/tun: 1
          killSwitch: true
          excludedNetworks_IPv4:
            - "192.168.0.0/16"
            - "10.10.0.0/16"
            - "172.0.0.0/8"
          excludedNetworks_IPv6: []
          env:
            VPN_PORT_FORWARDING: "on"
            VPN_PORT_FORWARDING_PROVIDER: "protonvpn"
            HEALTH_SUCCESS_WAIT_DURATION: "10s"
            HEALTH_VPN_DURATION_ADDITION: "31536000s"
            FIREWALL: "on"
            FIREWALL_INPUT_PORTS: 10095,8000
            FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/16,10.10.0.0/16,172.0.0.0/8"
            VPN_TYPE: "wireguard"
            VPN_SERVICE_PROVIDER: "custom"
            WIREGUARD_ENDPOINT_IP: "${WIREGUARD_ENDPOINT_IP}"
            WIREGUARD_ENDPOINT_PORT: 51820
            WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}"
            WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
            WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
            WIREGUARD_MTU: 1390
            WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 25s
            WIREGUARD_ALLOWED_IPS: 0.0.0.0/0
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: qbit.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          homepage:
            enabled: true
            group: "Media Downloads"
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENC}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      gluetun-auth-config:
        enabled: true
        type: configmap
        mountPath: /gluetun/auth/config.toml
        objectName: gluetun-auth-config
        readOnly: true
        subPath: config.toml
        targetSelectAll: true
      download:
        enabled: true
        type: nfs
        path: ${NFS_2_PATH_DOWNLOAD}
        mountPath: /download
        server: ${NFS_2_IP}
      ssdsafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_SSDSAFE_RIPTIDE}
        mountPath: /riptide/ssdsafe
      videosafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_VIDEOSAFE_RIPTIDE}
        mountPath: /riptide/videosafe
      videounsafe:
        enabled: true
        type: nfs
        server: ${NFS_IP}
        path: ${NFS_PATH_VIDEOUNSAFE_RIPTIDE}
        mountPath: /riptide/videounsafe