apiVersion: v1
kind: Secret
metadata:
    name: longhorn-minio-credentials
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EiJmNXZSm/Rnv6wrcM74JrY8T0w=,iv:NLMWZkmLhGo/Yc4JVoQ5aJgKR2+dAZgiNQ3/7ookX0U=,tag:M/oay3AdZ6QJtPPhvCWM/Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sihxvpNncgjy+Usnh3vnSj2WFWulQnDLinr6XL0jJYVgIMDByDYkXA==,iv:2dkk/YYtltP9jpdHN9PnYaVU8JukVdwdWWdI/nfDwtU=,tag:bLb9fJDS9OPCaj9Suin1GA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:fsjZM3USHOSS1DPQetZNNjTieBqNWZFBlA==,iv:Rc5OmFBXJyBjVfqi06yZmq2SQY7zTqv7741x1YooLUA=,tag:h8FYLwm0rFTmQI3g9F+wvw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbCtEMlFKeHFkT1B6SFNP
            ODE3bk9DZzRaYVozUndCR0Q1YWgrUFRaenhrClp1MEZSZzVKWWdaN1FWcjhWRE1C
            enpOMXcyNzFpMnFNeHBDSmFMMmptTFEKLS0tIGJmTTNuNjFaTmRlVWhYeW1SQWZU
            d0liamZtSXFVWUJlSktld0FiZGpMeXMKXMHy8mg+boIL23MnSrrAdXRnlncWdX0k
            dNFFmWy2dUQw1O8iSbhftdyghCun6eOz8LC6Wiyn+QUyYjRW+KKoAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T22:32:11Z"
    mac: ENC[AES256_GCM,data:XGIsb299X5yXLSXMG0cr9pR2X35vaLNsXvAhQkxjcywOaTPVfIYi8eEQBaohIPZqsH5NzBAqfU26JD74UYSXGxZjej4/Fr81BZuQ3xeFC48AsnDv1vRIpl1p3D9whBraLkfLvMCEeqsBSNjW9OFo/lp9AAYvYx0Dui9ZnUUpFQo=,iv:v9M5qDw2vwBSKp9LnMOabxvqzDM9gNKLf8MummXI5sI=,tag:wla2VyHmiroUoBvbEOqiwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
