apiVersion: v1
kind: Secret
metadata:
    name: longhorn-minio-credentials
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/FoMAF773zZDexxGUo+72hl/qmg=,iv:2Bw7VpNGpYT923TKOT1EgHA5SrvE2Ow/NDMyLlk5A60=,tag:oAYQjgZV05XraxFl/4v53A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5FgxJKlLmBGn2JWkd/4uc80qN9H40Z0lwx8uDnzomBfI2pSUKo94kQ==,iv:GszOMaAP+p3W8a/EHM1UPOXpT5veAWgM28f5baOG/CQ=,tag:jEJQdOwFXAWL+29HDedxwA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:TMA0ANdGYw0X+vH2cG3f+SbCvrbC4Ht8sQ==,iv:3XUw9vP8DW/rkPhdGFkMjCfwMVJzqN1PCFIqW8rPrgs=,tag:xvjJE3Gh4EgqE+kIJbeX5w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVTRvUk1jajlCUHU5STlX
            SlVDaWc2NjdJcU8wMCthWXI3ZnpXNk5BaUdJClVOK1VhRko1YlB3cnZhRWNFbVRU
            UE5Qb1pGZVZhbWl3TlVRMk9aU2VZNlkKLS0tIFltQmNwWkJOSjlaTFFreVRoVThl
            Yk5vYjduVHV4WURncDBRd3pkUmpoRWsKjS60Z9ThkFdh1d7sVUT9fpNZlhS5HoQ3
            yPNer/gsoVXpybucr6Abn8xGWwFXsrSbHjc2/hXioxoBo82HT2/nlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:53:39Z"
    mac: ENC[AES256_GCM,data:/w7MF04wNQqN012KMUw0ayg1Plb9eqBEDBFZoVm5EUvNjYqeQcb3lfcaQCkpUMTyr5Wp18p7FSaStuZ/djxcKGQnYPkGplaXe22wguYV8dCAFQqYMEU8PWvGat8bEW4OMt4efFXxabiLS0aueTHIdgjrTugBK9kVqNr+y/fRzYM=,iv:jRS3E6vvdfkR7VmKpPKMRCWxGuALRP5gaLbg5eGyVvk=,tag:lTn++T8jrA1FVGC7Z9iaCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
