apiVersion: v1
kind: Secret
metadata:
    name: longhorn-minio-credentials
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:19/Y439RtVwMxFZmIHwBfc6kEaQ=,iv:N1MEEUq6Xq0i5WgDarhG/XlHpqnXrhGAsm4ukl2bhNo=,tag:ZcB16bu+Bo358l9BKmuiOQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Amcrm0yQkFLvvks65ww9s+LUa+M71W62GjS3EORcDNNea5rdyUaBEA==,iv:OwqadS3SEhUNTDtufZZk9CusWyclQnODI+Lemg+16mg=,tag:b7t8UJUrR1z1DVBFmn+Xbg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:bTusbbuLyk3VMqDYQiTyDaCMFaAGxfK7JQ==,iv:I6SxzybLeWwF/QxMWvAeCKXxt8uEM4ZA7bqhv5oZEYY=,tag:3Ibew22d7ZvrF+AfLGg80g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eWxUeGd0aVFrdGwyZEE1
            bHJuYjZ4Nnl4TDdZcWlKVnRaQ0JFMkJrMVZjCi8vNXNCMnhvSVVLdGVOb253OXN2
            R2VGQzdJN1J6UGZSZ1VYTEltK1BZSFEKLS0tIHZ1RlJtMXNnck55U0U0YTBxekNY
            UkNNd2JFVElobkEzcTZnWC9PRnBqM1UKBozYPKUFuFWc+omWVwYecMsgDf/BbUpc
            rWCmeDP30zsmh0Ty+ZfsijzPvUdjHFpL1e3CYS7Gtrv+1tEvoU97Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:05:19Z"
    mac: ENC[AES256_GCM,data:dhQ3KbNwCdy8HaLnFthwJD9mRcHKS6GaEu545RwpB+9mZDNRr1GEoNnxfVNgMjqSLSo9msuTlGq115pfSys/h9KfVlNQjt1hrXE1Osk/7N9/oVCmEs8eMQoF671OVBuROm8UFs1pKCZ+1Ej5OCDvVnscQvj9s52jEMHn3WZ3Zcw=,iv:GYq1CsQAIb70n6GpIX0VTdip+RppdFsdwf9bsWblRDI=,tag:0fXJii3vods2wHfwu6xtYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
