apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crafty
  namespace: crafty
spec:
  interval: 5m
  chart:
    spec:
      chart: crafty-4
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: craft.${DOMAIN_0}
    resources:
      limits:
        cpu: 2000m
        memory: 15Gi

    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENC}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      servers:
        volsync:
          - name: servers
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      logs:
        volsync:
          - name: logs
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      import:
        volsync:
          - name: import
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      backups:
        volsync:
          - name: backups
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true