apiVersion: v1
kind: Secret
metadata:
    name: doorbell-secrets
    namespace: doorbell
type: Opaque
stringData:
    Jwt__Secret: ENC[AES256_GCM,data:EqVzXGw2xsitJap98jsJUazH5KKw03dHAA0xeSlGu6SBXGbwP6SlSHPljmRlK6qzbNTM7JXhyNGJt4uPqNLlQw==,iv:2NyhPNacjNcvmnK0rar7x+bxyTonIp5jnma9mqFQu/E=,tag:3+M9Z5ZpzbNHsUYhQX0ZzA==,type:str]
    Auth__DeviceToken: ENC[AES256_GCM,data:4fLOe1jfDCPDm6dVGgeao1WoL86i2xCOkw0ofcHy8g0MJRp2mEat6y43T6q3ErGO8GKZJ0QuEPrOxuTfb2yzSw==,iv:v/8tiMNxOCbe5zik2qT/0vtRYtxw+IJrtPSLCZ6iOfI=,tag:gWaFVMevlrViMfnoe10lFA==,type:str]
    Auth__SeedAdminPassword: ENC[AES256_GCM,data:0Dry2PdFT6IwnL4KmZEnLzj1lJBi1K1/,iv:0vl6N6VJwCvMPZelCiZLZNXdJydc5YO0IXFSX2VlgZA=,tag:+mS2gaqAszT1qrEVbPiz9Q==,type:str]
    Ice__TurnSecret: ENC[AES256_GCM,data:KlTnsHeajiXcWamykp7+a4hw2q8hawXI5LXixaMn2tgUdFlvQ36NSeNe5MCpzya7y+A8l8wiKUt7OHW/YLBCNw==,iv:brwI89yHOkfFxrzB/atv6nZGVj2X2sqDe1UdrRnOLPA=,tag:t+JWCuDOuq3khFTi8ygz4Q==,type:str]
    Push__PublicKey: ENC[AES256_GCM,data:5ernrNuOUQt4TofbKtHiwhU1V0zIlZ6yQOY37dDD8NfpVRGoge1xl3WmBhXss87xdnTMM/x475TghapTVQr0U5PnEIz5ZD0vcQpIZ2WCawfkR17OGkxM,iv:lszXbDLuUj87+9TwRm5Xe3lfqTaTEPmIhZ81g5MJyY8=,tag:G/18eGbBQyC39QLAGVvXLQ==,type:str]
    Push__PrivateKey: ENC[AES256_GCM,data:h+qSn3Ms12YXlIRZOzrQocIZamzGwrcX1v2vmTyTMxUk9ccPIkn8fc1Jkg==,iv:vswAglx1XNMQ1KICvoPeX8WBDrMQ1v+JBiyB+EMcozs=,tag:N8QbpREKBv5Jz9HFsdaRTQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNXhIbWtoWjJqZXlaMUZU
            aGpxVHdOWmsyL25yVWFiL2UxdG16c1pKRUhNCnMxRjkzS1hQTHZXYXljaEFyTFpN
            QXRTczZDczAwZ2YvZ2xDZFhDdG1oYk0KLS0tIHQ0Rk8zdFkyNzZQemdLUmhQRW5U
            dk1zMTd3QUJtSWRnc3FJb0tiWWVBZnMKLvUPH0B1EUwBMl5e6lIAkMaFgmdioGgr
            tRqpp+OT9dYSi71BHw4JMVPZsE6R279aOOSAQlV8pUZT6K9fhVh14g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T14:15:59Z"
    mac: ENC[AES256_GCM,data:HGu0Q/J5iX9YTsMWaq0UBd2ayzYrhkHR3EjFJU81GoZv7NEV3c7BhVBIHMpo16ulLPRokaCC+IGVlZeiWIUefuD6vs4OJZNWsxc7XWDePsDiL17zYjKKwGPN/dvFaj8kmZpVbfG7cH3L2VRDyz2qAQwDjqSQKnuhFzpMnW3F2VI=,iv:k98h0PQnaM9W5xytJEH2iOtWporOKJDNN7ieltcIBZc=,tag:xX91LzgPpnkJKFGfZUpQTQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
