apiVersion: v1
kind: Secret
metadata:
    name: doorbell-secrets
    namespace: doorbell
type: Opaque
stringData:
    Jwt__Secret: ENC[AES256_GCM,data:SLpGkTOqKMGkH6kd+whmDJtYSWyvUr+tx/wfP6hzZSqE349JI89TS0WPxLm5KrXrlHb2hiM/qmvj8GoMRDJnaA==,iv:5DAigfvbnHbNRJYEtgwBiZuUmUgLktUrlODgA555DWY=,tag:ppn9kraWXtAMwIc9bePf2w==,type:str]
    Auth__DeviceToken: ENC[AES256_GCM,data:Jx1G0hNfbMmGctsLAmCNeeEHWAfjjgBO5gk6m9a1m6cdnuemrRRCLv15EsXHwAzGdmtEcnhns8opu5JfaOKJ+Q==,iv:GvdKn0vVHPzC8fvkeAgm1N5HJxdRDU0F+btrHvDCuRs=,tag:iR8KMZKo4nnTsm2bC3tnqQ==,type:str]
    Auth__SeedAdminPassword: ENC[AES256_GCM,data:g8TP66kR9u0/kOobdl49YdoxrC+vWVMX,iv:oZSFCmkhtEugXisHwWxZEookoVb/xR3HNvWZ6QY1wGg=,tag:rhqH4WjrLGoYhqWn442+FA==,type:str]
    Ice__TurnSecret: ENC[AES256_GCM,data:eIN9vqty3PnVkf39QmgyKPzlzO4VEwRmjTduviCJm0lZW0uiVYNbOJe9G6sAAu1C5dmZaZ8U46//dB7+swDu4A==,iv:VEjbsEajOAmFthRashGsiIMa+qNb3HoaomAw+jaZb1g=,tag:M5Li9TuThMNECYEdDHQnQA==,type:str]
    Push__PublicKey: ENC[AES256_GCM,data:/eo7CrMe4780ZDySSjivg/JRbdFGHPVdNIMI1LeqnLb/Jv+yB5PvAN2FJP8f/a0sROHyPLhCVEmVnH3CDKVYDBIQustaicgNyiKrPvujgtZgEfbNTsOn,iv:LqY5adJZ7mDWqQ4rob4RbMCFB8ynWGtZTfwEEPoCWJ4=,tag:Nubo2RH7wzHyCBFFpi4IhQ==,type:str]
    Push__PrivateKey: ENC[AES256_GCM,data:1AcTTgjCVPf9ThoNobMLD8HHmnfmSpLvpRYJ5M1ofm3zBC/bNhAXZ7EjCg==,iv:5kSP74+sD/mgj6712iy/8XC9xMpV7FdW6eudkQDP4/Q=,tag:AYfD79kBkocinG9FtrpNeQ==,type:str]
sops:
    age:
        - recipient: age1mgtvp6pu8u3jv79hqdy7sa6299y2wp25xqjyt6550hv2g6fqzs7shhav84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjODlKUWlMeHNBbkxPWG10
            dzRuUlpZODRnWHB0cTFTUnRYRmc4bEZ5RkJZCjBvbzBGdU83b3RZc3haTXVxRGo5
            UEM1OWt4ajJ3VFpiTkFKRDRjMzd2LzQKLS0tIG9zTi9iS1FCaGVsYms0dlJoNXhL
            dW40NEV5QnV1T3lHTVBqNTYybGNMUDgKw2hd7RlYvJt+RByIbxCEUPsI3M8hFFI5
            +qDIsRn8hZVgUA2Bjj2+9tVyQ7TX+s1t2dZEsNh3JwTBb+aBrjlwCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T14:31:31Z"
    mac: ENC[AES256_GCM,data:e95IXmhlQ9Y/BynYRWxIMivShua4TSMYaZyEfVpAnTwKrFVZrbKBM5xib4bsZjYYv2jbR+wc8JpeR0bND2rqoJLbME2q4je+USUnhuds6lyRyg/xS8srRCNwrmZVEW3xeaw3ppJu6TlGUqzLTpdHke80R/2d9btgOPZHtEUZxRI=,iv:L5cups79dsWleyupcylTADMjRJJIn7BgRiwMQAF2Z0Q=,tag:hd0HAi3qY1EvLgXiLZDEPQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
